name: ankara_metro_tracker
description: Ankara Metrosu sensör tabanlı takip ve navigasyon uygulaması.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Sensör verileri için (İvmeölçer, Jiroskop)
  sensors_plus: ^6.1.1
  
  # State yönetimi için (Main.dart ve UI iletişimi)
  provider: ^6.1.1
  
  # Cihaz titreşimi için (İstasyona yaklaşırken uyarı)
  vibration: ^1.9.0
  
  # Zaman ve tarih formatları için (Tasarımdaki saat ve tarih)
  intl: ^0.19.0
  
  # Yerel veritabanı (İleride durak verileri için gerekecek)
  sqflite: ^2.3.3
  path: ^1.9.0
  flutter_activity_recognition: ^2.1.0
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Tasarımlarında kullandığın logoları buraya eklemelisin
  assets:
    - assets/m_logo.png
    - assets/icons/b1.png
    - assets/icons/m2.png
    - assets/icons/m4.png
    - assets/icons/a1.png
    # Eğer varsa bir istasyon haritası görseli:
    # - assets/metro_map.png

  # Tasarımındaki dijital veya özel yazı tipleri için (Opsiyonel)
  # fonts:
  #   - family: DigitalNumbers
  #     fonts:
  #       - asset: assets/fonts/digital_numbers.ttf
